# Copyright 2022 Linkall Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http:www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: Service
metadata:
  name: config-gateway
  namespace: vanus
spec:
  selector:
    app: vanus-gateway
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
      name: vanus-gateway

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-gateway
  namespace: vanus
data:
  port: 8080
  controller_addr: "127.0.0.1:2049"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanus-gateway
  namespace: vanus
  labels:
    app.kubernetes.io/name: vanus-gateway
spec:
  selector:
    matchLabels:
      app: vanus-gateway
  template:
    metadata:
      labels:
        app: vanus-gateway
        app.kubernetes.io/name: vanus-gateway
    spec:
      containers:
        - name: gateway
          image: linkall.com/vanus/gateway:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: config-gateway
              mountPath: /server/config/gateway.yaml
              subPath: gateway.yaml
      volumes:
        - name: config-gateway
          configMap:
            name: config-gateway