name: "test-1"
ip: "127.0.0.1"
port: 2048
etcd:
  - "127.0.0.1:2379"
data_dir: "~/tmp/data/vanus"
topology:
  service_a: "127.0.0.1:2048"
metadata:
  key_prefix: "/wenfeng"
embed_etcd:
  name: "etcd-1"
  # relative path to ${data_dir} above
  data_dir: "etcd/node1"
  client_addr: "127.0.0.1:2379"
  peer_addr: "127.0.0.1:2380"
  clusters:
    - "etcd-1=http://127.0.0.1:2380"
#eventbus:
trigger:
  storage:
    keyPrefix: "/xdl"
    serverList: [ "127.0.0.1:2379" ]